# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: myphoner
email: contact@myphoner.com
description: > # this means to ignore newlines until "baseurl:"
  Internal documentation for myphoner.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://liisberg-consulting.github.io" # the base hostname & protocol for your site
twitter_username: myphonerapp
github_username: liisberg-consulting

# Build settings
markdown: kramdown
exclude: [log, spec, tmp, vendor, Gemfile, Gemfile.lock]
